export const cuisineList = [
  "Indian",
  "Italian",
  "Mexican",
  "Thai",
  "Chinese",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Mediterranean",
  "Greek",
  "Spanish",
  "French",
  "German",
  "American",
  "Asian",
  "British",
  "Caribbean",
  "Irish",
  "Russian",
  "Australian",
  "New Zealand",
  "African",
  "Middle Eastern",
  "South American",
  "European",
  "Latin American",
  "Cajun",
  "Cuban",
  "Puerto Rican",
  "Southwestern",
  "Southern",
  "Central American",
  "Hawaiian",
  "Himalayan",
  "Hungarian",
];
